DROP TABLE IF EXISTS bookmarks;

CREATE TABLE IF NOT EXISTS readLater (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  tag VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL
);
